# Created using wingetcreate 1.2.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.4.0.schema.json

PackageIdentifier: TiberiusCN.HaloTeamBalancer
PackageVersion: 1.2.0.6
Installers:
- InstallerUrl: https://github.com/coeus89/HaloTeamBalancer/releases/download/1.2.0.6/HaloTeamBalancer.zip
  Architecture: x64
  InstallerType: zip
  NestedInstallerType: exe
  NestedInstallerFiles:
  - RelativeFilePath: publish\setup.exe
  InstallerSha256: 5E7FF60BED535E20C3D3B48CA55AAC3416F2D67B771AC2C10D9841C401DBA1D0
ManifestType: installer
ManifestVersion: 1.4.0
